#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
$APPDIR/java/bin/java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/Attuning_Fork.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/core.jar:$APPDIR/lib/tritonus_share.jar:$APPDIR/lib/jsminim.jar:$APPDIR/lib/mp3spi1.9.5.jar:$APPDIR/lib/tritonus_aos.jar:$APPDIR/lib/jl1.0.1.jar:$APPDIR/lib/minim.jar" Attuning_Fork "$@"
